language: R
cache: packages
sudo: false
warnings_are_errors: true

matrix:
  include:
  - r: release
  - r: oldrel
    env: _R_CHECK_FORCE_SUGGESTS_=false

addons:
  apt:
    packages:
      - libgsl0-dev # for topicmodels
      - libxml2-dev # for XML, a dependency of quanteda

r_packages:
  - covr
  - cRypto

env: _R_CHECK_CRAN_INCOMING_=FALSE

after_success:
  - Rscript -e 'library(cRypto); codecov()'
